Feature/#113 namespace (#288)
* added user account endpoints

* disable homepage links when user is not logged in; only prompt admin about org identity

* disable resources drawer if user is not logged in

* disable links in header if user is not logged in; login/logout button

* init authentication service

* navigate to landing page on logout

* created user accounts admin page

* added route guarding to homepage routes

* user account object & role enums

* fix formatting

* anonymous login/logout

* transform http requests to include necessary headers

* check for null email field

* add login/logout options to hamburger menu

* disable hamburger menu routes

* added route guards to stix routes

* restrict/disable unauthorized user actions

* add help icon to data source list page

* Added condition to check if user is logged in, to display their name on objects they've edited

* Added missing created_by_user_account field in stix object workflow

* Subscribe to RestApiConnectorService to display username for workflow user account id

* Only update the identity name if the field is modified_by

* Added timer count to SetTimeout before navigating away from edit Object page for most up-to-date modified time

* load session in auth guard

* get user account object from session response

* oidc login

* remove tap utility for user accounts

* update app version number

* display user account icon in header

* user account validation for username

* alert user on inactive/pending status

* show org identity dialog on admin login

* event emitter for admin pop-up

* update function documentation

* responsive header design

* fix for issues retrieving collection bundles & indexes by URL

* restrict collection actions to admin only

* restrict collection index actions

* fix header styles

* consolidate collection manager service into rest api service

* add edit roles to routes

* use route data to authorize users with editing capabilities

* fix function call

* update collection index view based on roles

* bug fix for reloading objects on save

* bug fix for collection category label mismatches

* bug fix for creating and saving new collections

* remove workflow state from collections

* reroute before re-loading objects

* bug fix for authorizing routes by role

* update changelog for 192, 266, and 191

* documentation updates

* indication of pending users on admin pages

* update user accounts endpoint

* fixed sonarcloud code smells

* hide badge if there are no pending users

* responsive design improvements for header

* update name of credential header

* Feature/#193 user accounts page (#275)

* Added skeleton of user accounts table, took styling from stix-list table

* Fleshed out user accounts table, with hard-coded filter options (might want to change to constants somewhere instead), errors with converting Paginated to Array

* Lint

* Added isAdmin boolean, for ability to change user roles

* get user account object from session response

* oidc login

* remove tap utility for user accounts

* update app version number

* display user account icon in header

* user account validation for username

* alert user on inactive/pending status

* show org identity dialog on admin login

* event emitter for admin pop-up

* update function documentation

* responsive header design

* fix for issues retrieving collection bundles & indexes by URL

* restrict collection actions to admin only

* restrict collection index actions

* fix header styles

* consolidate collection manager service into rest api service

* add edit roles to routes

* use route data to authorize users with editing capabilities

* fix function call

* update collection index view based on roles

* Calling save user API, need to debug

* Updated pending color to duller yellow, and updated text color for dark mode

* Updating saveUser()

* Calling putUserAccount() instead of post... to update account--works, but currently needs to construct a new UserAccount object every time in order to call UserAccount class public methods

* search works

* Fixed sonarcloud accessibility issues for user acc table

* Added approve user functionality to user accounts page

* Fixed paginated object erorr

* Updated user role select dropdown

* Added enum for status values

* Fixed typo

* Added register buttons and call, which mimics the login() call to check for authn type === oidc, and then sets the current user as undefined until they are approved by an admin

* Cleanup

* Fixed api endpoint

* User should not be able to change own role

* Only show register menu link if authnType is oidc

* Fixed pagination style on user accounts table; added ability to change status if user is admin

* Removed onDestroy by unsubscribing to authn service on complete() instead

* Fixed serialize() issue (it was calling this.deserialize() but result.serialize(), when both should be calling this and not result)

* Added banner text detail for pending accounts

* Changed to successful

* Fixed filter object and function

* Added nothing here message

* Register button should take user to oidc login, then make a post call to register endpoint

* No need to check for isLoggedIn on registering, anon register is handled by api

* Styled user status to chips, even when dropdown is enabled

* Fixed applyFilters()

* Added /register path to landing page, which is handled in the App component, to check user status after registration

* Call getSession() on register callback to assign current user to session; added register subscription in app.component.ts; moved check status in app.component.ts to else case to remove race condition in checking while assigning undefined to current user account

* Fixed filter function

* Remove 'none' from user account filter options

* Fixed disabled step icon color in paginator

* Forgot to commit removed check status code in app component

* Stop multiple calls to getSession() on app load

* Add none to role options

* Redirect router to home after /register path is handled, to remove from url

* Added reroute to added subscription, after handle register is called

Co-authored-by: Charissa Miller <48832936+clemiller@users.noreply.github.com>

* updated changelog to include 193

* use status enum & code cleanup

* Added usability to applyControls() on user accounts table pagination (#286)

* Added usability to applyControls() on user accounts table pagination

* Updated getAllUserAccounts() to apply multiple status and role queries to api call parameters; fixed pagination controls, search and filter functions on user accounts page

* Call get accounts if no filters/search is applied for paginate to work

* update role enum & set role to none if status is changed to pending or inactive

* update changelog

* remove unused imports

* add role set for maintainablility

* Refactor 'Organization Identity' component page to 'Organization Settings'

* Added new ui for editing mocked namespace, for now

* Added mock api calls for organization namespace settings for now

* Added TODO

* Fixed accidentally overwritten merge conflicts for org-identity -> org-settings change

* Fixed accidentally overwritten merge conflicts for admin page buttons

* Use get namespace endpoint

* Renaming range to range_start to match endpoint

* Fixed namespace object sent in POST call

* Added namespace interface, and strictly typed functions with namespace object

* Fixed field validation for namespace prefix

* Removed todo for org settings popover

* Fixed validation for range start input; default to 1000 if no input

* Added loading message for namespace settings

* Updated description for namespace settings

* Added restAPIService and supportsNameSpace to constructor of relevant StixObjects

* Fixed error: Property 'name' does not exist on type 'unknown' by changing dot operator to square brackets to access object fields

* Added information on new object ATTACK ID input field

* Only generate namespace attack id for Matrix without id validator format

* Fixed dot operator error on accessing object field

* Fixed validation for stix object attackIDs, to allow for namespace prefixes

* Updated changelog.md with links to GH issues

* Moved attack ID w/ namespace generation to ngOnInit() of each Stix Object that supports namespacing, instead of inside the constructor(); added the supportsNamespace: boolean field to Stix Object class

* Make sure that Stix Object view only generates ATT&CKID if in editing mode

* Revert changes to StixObject constructor call

* Fixed default range_start and invalid input settings

* Set prefix to be uneditable in attackid-edit.component

* Show hint if there's a prefix

* Fixed regex rules, and don't generate ID if object already has an ATT&CK ID

* Generate namespace with object group prefix even if namespace prefix is not available

* Validate namespace settings before allowing user to save

* Fixed code smells; fixed bug with counting latest object with namespace settings

* Added parent technique form field on create a new sub-technique page

* Added generate button to attackid-edit.component.html

* Updated generate attack ID function to accommodate sub-techniques

* Added gentle reminder to user as a hard-stop if generating id for sub-technique w/o a parent chosen

* Removed generate attack id call from all object view pages (moved to attack id edit property component instead)

* Fixed ID counting bug, moved mat-hint for generate attack ID feature to mat-tooltip

* Fixed decimals for sub-technique ids

* Do not generate attack id for matrix, just add namespace prefix

* Fixed get sub-techniques of technique call; fixed bug in calculating latest ID

* Fixed decimal adding error

* Added relationship call after saving object

* Fixed namespace settings form fields

* Fixed remaining bugs; strongly-typed namespace to string in frontend, but ensuring to always send number to api; added loading icon to parent techniques in create sub-technique form field

* Fixed code smells

* Fixed StixObject as Technique bugs

* Update changelog.md

* Update changelog.md

* Disable parent technique field if still loading objects

* Prepend prefix to object name when editing object attack id

* Allow namespace prefix to be null

* Removed dead code

* Fixed org settings field input validity check

* Fixed generate ID; allow users to set namespace settings to blank; and append prefix if user types in ID manually

* Fixed appending decimal count to generated sub-technique attack ids

* Fixed check for finding subtechniques of parent technique

* Only create relationship if creating a new sub-technique object

* If user changes a parent technique for a sub-technique, revoke previous, and clear attack ID field to force users to create a new id; Fixed object name label UI bug

* If organization range setting is defined, set it to the next available unique ID in range

* Use the next highest available ID, if range is available, unless range is higher

Co-authored-by: Charissa Miller <48832936+clemiller@users.noreply.github.com>